### ISSUE TITLE
ERROR in ./src/components/FeaturedProjects.jsx

### ISSUE THREAD

**Issue by bsed** [jxnblk/jxnblk.github.io#9]
```
ERROR in ./src/components/FeaturedProjects.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ./SkullcatLogo.jsx in /home/kelvin/workspace/blog/src/components
 @ ./src/components/FeaturedProjects.jsx 47:23-52

ERROR in Error: Cannot find module "./SkullcatLogo.jsx"
    at webpackMissingModule (bundle.js:35736:89)
    at Object.defineProperty.value (bundle.js:35736:184)
    at __webpack_require__ (bundle.js:30:30)
    at Object.defineProperty.value (bundle.js:35637:29)
    at __webpack_require__ (bundle.js:30:30)
    at Object.VERSION (bundle.js:20488:17)
    at __webpack_require__ (bundle.js:30:30)
    at Object.<anonymous> (bundle.js:60:13)
    at __webpack_require__ (bundle.js:30:30)
    at bundle.js:50:18
webpack: bundle is now VALID.
```

**Comment by bsed** [comment]
No one answered. Close
